version: '3.4'

services:
  blazorapp1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapi1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

